from model.model import (
    Base,
    SysUser,
    StudentAdminService,
    StudentPsychProfile,
    StudentPsychAlert,
    StudentFeedbackTicket,
    CrmLead,
    EmployeeDailyReport,
    StudentScore,
    CourseProject,
    EventLecture,
    EventRegistration,
    StudentAcademic,
    StudentStudyAbroadProgress,
    Notification,
    OrgDepartment,
)

__all__ = [
    "Base",
    "SysUser",
    "StudentAdminService",
    "StudentPsychProfile",
    "StudentPsychAlert",
    "StudentFeedbackTicket",
    "CrmLead",
    "EmployeeDailyReport",
    "StudentScore",
    "CourseProject",
    "EventLecture",
    "EventRegistration",
    "StudentAcademic",
    "StudentStudyAbroadProgress",
    "Notification",
    "OrgDepartment",
]
